language: go

before_install:
  - go get github.com/mattn/goveralls

matrix:
  include:
  #- go: "1.12.x"
  - go: "1.13.x"
    env:
      - GO111MODULE=on

install: true

script:
  - make test
  - $GOPATH/bin/goveralls -service=travis-ci
