language: go

before_install:
  - go get github.com/mattn/goveralls

matrix:
  include:
  - go: "1.11.x"
    script:
      - make test
      - $GOPATH/bin/goveralls -service=travis-ci
    env:
      - GO111MODULE=on

install: true
